services:
  frontend:
    image: simonapi-frontend:latest
    container_name: simonapi-frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simonapi-frontend.tls=true"
      - "traefik.http.routers.simonapi-frontend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.simonapi-frontend.entrypoints=websecure"
      - "traefik.http.routers.simonapi-frontend.rule=Host(`hub.abler.tirol`) && PathPrefix(`/`)"
      - "traefik.http.routers.simonapi-frontend.priority=10"
      - "traefik.http.routers.simonapi-frontend.middlewares=simonapi-frontend-compress"
      - "traefik.http.middlewares.simonapi-frontend-compress.compress=true"
      # Interner Container-Port des Frontends (ggf. anpassen)
      - "traefik.http.services.simonapi-frontend.loadbalancer.server.port=80"

  backend:
    image: simonapi-backend:latest
    container_name: simonapi-backend
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env  # must contain DATA_DIR=/data/signpacks and IP_HASH_SECRET=<openssl rand -hex 32>
      - /home/simon/simonapi/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simonapi-backend.tls=true"
      - "traefik.http.routers.simonapi-backend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.simonapi-backend.entrypoints=websecure"
      - "traefik.http.routers.simonapi-backend.rule=Host(`hub.abler.tirol`) && PathPrefix(`/api`)"
      # Strippt das Prefix /api bevor es an den Service geht
     # - "traefik.http.middlewares.simonapi-backend-strip.stripprefixregex.regex=/api"
     # - "traefik.http.routers.simonapi-backend.middlewares=simonapi-backend-strip@docker"
      - "traefik.http.routers.simonapi-backend.priority=100"
      # Interner Container-Port des Backends (ggf. anpassen)
      - "traefik.http.services.simonapi-backend.loadbalancer.server.port=3000"
    depends_on:
      - postgres
    networks:
      - postgresql

  postgres:
    image: postgres:17.5-alpine
    env_file:
      - ./conf/postgres/.env
    volumes:
      - ../postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d simonapi']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - postgresql

networks:
  postgresql:
    name: NET_POSTGRESQL